# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a9d6a0ea06f0d8d48fd0d1b0ab08f4d5fa43a77b27698bf696e70051ba4b4d789be67ca4392ba6be3fc189db0c59a7b7635d09ef62334db2c3fb751b3cf622

test:
  secret_key_base: 8072664ab92e867204556cc9707f6711a633215f092018f326200a5dc77a167f6c29ac9076cb1e1703c8de0a7076304474ba3292ff450237d64cc6bf974a931a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
